# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: Github Blog Template
url: http://liuxiaoyu8858.github.io
feed: /atom.xml
author_info: <a href="http://liuxiaoyu8858.github.io/">liuxiaoyu</a>

myblog:
  gavatar: images/2.jpg
  gpname: liuxiaoyu 
  linkedin: http://www.linkedin.com/in/liuxiaoyu
  github: https://github.com/liuxiaoyu8858
  email: mailto:396204209@qq.com
  coverimgs: []
  postbgimg: []

categories: [python, books]
